Document the LEAPP_ENABLE_REPOS envar
oamg/leapp pull request #662
Opened 2020-09-08 11:39 UTC by pirat89

That's only missing envar that is not documented and it is supported.

2020-09-09 11:51 UTC, camandel commented on docs/source/el7toel8/envars.md
> +Specify erpositories (repoids) split by comma, that should be used during the
Typo in "erpositories"

2020-09-09 11:52 UTC, camandel commented on man/leapp.1
> +Specify erpositories (repoids) split by comma, that should be used during the
Typo in "erpositories"

2020-09-09 13:36 UTC, drehak requested changes

2020-09-09 13:36 UTC, drehak commented on man/leapp.1
> +the \fI--enablerepo\fR option instead of the envar.
Please put this on one line.

2020-09-10 09:42 UTC, pirat89 commented on man/leapp.1
> +the \fI--enablerepo\fR option instead of the envar.
done

2020-09-10 11:32 UTC, drehak approved these changes

2020-09-10 13:11 UTC, merged