os.path.ismount workaround to detect bind mounts
oamg/leapp pull request #679
Opened 2020-11-25 21:18 UTC by vinzenz

Previously os.path.ismount does return False for bind mounts if they
come from the same partition. This PR fixes this issue by checking
/proc/self/mounts if the mount exists.

This patch bumps the framework-version to 1.4

Task: OAMG-4171
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1901440
Signed-off-by: Vinzenz Feenstra <vfeenstr@redhat.com>

2020-11-26 08:57 UTC, Rezney requested changes

2020-11-26 08:57 UTC, Rezney commented on tests/data/mounts_fix/mount_withoutbind
> +devpts /dev/console devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666 0 0
Please add a new line at the EOF.

2020-11-26 08:57 UTC, Rezney commented on tests/data/mounts_fix/mount_withbind
> +overlay /usr overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/E6QDTSDO4R6FU7IUN3SKWB2M6F:/var/lib/docker/overlay2/l/N7VEADMERCHKZBYU3YK23MTCI6,upperdir=/var/lib/docker/overlay2/fca5eaf608e4805
Please add a new line at the EOF.

2020-11-26 08:57 UTC, Rezney commented on leapp/utils/workarounds/ospathismount.py
> +                target = line.split(' ')[1]
Just curious, under what circumstances it will not have the target?

2020-11-26 08:57 UTC, Rezney commented on leapp/utils/workarounds/ospathismount.py
> +        print("Path {path} does not exist".format(path=path))
What about printing to stderr here?

2021-01-15 12:06 UTC, vinzenz commented
This PR is not fixing anything related to the PR, removing it.

2021-01-15 12:06 UTC, closed without merging