Replace leapp-pr-welcome-msg-bot with GitHub action
oamg/leapp pull request #712
Opened 2021-06-07 12:55 UTC by andywaltlova

For working example see [my test repo](https://github.com/andywaltlova/actions_test_space/pull/14)

(Same PR in leapp-repository)

2021-06-09 12:12 UTC, Wecros requested changes
Otherwise looks good. Good job with linking the private test repo :+1: Will merge after the change.

2021-06-09 12:12 UTC, Wecros commented on .github/workflows/pr-welcome-msg.yml
> +# In this workflow should NOT be checkout action - because of security reasons.
Small nitpick: should -> there should

2021-06-09 13:21 UTC, andywaltlova commented on .github/workflows/pr-welcome-msg.yml
> +# In this workflow should NOT be checkout action - because of security reasons.
Fixed

2021-06-09 13:55 UTC, Wecros approved these changes

2021-06-14 14:56 UTC, pirat89 commented
@Wecros do you plan to merge it?

2021-06-14 15:16 UTC, Wecros commented
> @Wecros do you plan to merge it?

Well yes, if I could.

2021-06-14 16:48 UTC, Wecros commented
leapp-ci build

2021-06-15 13:08 UTC, Wecros submitted a review, later dismissed

2021-06-15 13:28 UTC, Wecros commented
@pirat89 Should I wait for the `e2e` issues to be fixed or merge it?

2021-06-15 17:00 UTC, vojtechsokol commented
Fixed e2e tests on staging passed: https://url.corp.redhat.com/f29fb5a

If it's not a pressing issue I suggest to wait for the fix to land in production (end of the week at the latest), then rerun the tests and merge.

2021-06-21 08:28 UTC, jmikovic approved these changes

2021-06-21 08:28 UTC, merged