Add default upgrade_paths generation
oamg/leapp pull request #740
Opened 2021-11-02 14:33 UTC by fernflower

For POC leapp.conf will store basic information about possible
upgrade_paths. Maybe will move to some other place later.

2021-11-03 08:34 UTC, pirat89 requested changes
this is bad by design as the leapp has nothing to do with specific upgrade. we spent a lot of time to separate logic, this data cannot be part of the leapp

2021-11-03 08:51 UTC, fernflower commented
@pirat89 We can make it a leapp-repository specific config file then.

2021-11-04 14:26 UTC, pirat89 requested changes
There is still the connection to the upgrade paths, which I mean in the way that we should not see any PR working anyhow about any upgrade paths..

In the framework, only the generic solutions are expected. We do not expect to install some upgrade_paths notes when people are going to convert. THe logic about upgrade paths has to be purely just in the leapp-repository located.

2021-11-05 10:51 UTC, fernflower commented
> In the framework, only the generic solutions are expected. We do not expect to install some upgrade_paths notes when people are going to convert. THe logic about upgrade paths has to be purely just in the leapp-repository located.
The framework will be used for 2 things - conversions and upgrades. I suggest we add a dedicated section about 'upgrades' to the leapp config where all upgrade-only-specific config file references go, like upgrade_paths. 

The latest commit should give you the idea.

2021-11-16 13:13 UTC, pirat89 commented
closing regarding the investigation.

2021-11-16 13:13 UTC, closed without merging