Add Makefile target for building RPMs locally and in containers
oamg/leapp pull request #792
Opened 2022-08-04 15:47 UTC by matejmatuska

Add `build` target to build locally and `build_container` to build
locally in a container. Building in containers has the benefit of being
able to build on all the different platforms e.g. both on  el7 and el8.

Run `make build` to build locally.

Run `make build_container` to build in a container. Note that
BUILD_CONTAINER environment variable must be set.

Run `clean_containers` to clean up container images used for building.

The containers are built from Containerfiles in `res/container-builds/`.
Since Containerfiles for all the Fedora versions would differ only in the `FROM`
statement, a generic Containerfile `Containerfile.fedora_generic` is
used and the `FROM` statement is inserted in the Makefile.

For el7 builds CentOS 7 container is used, because rpm-build package
is not available in ubi7 image.

Builds cannot be run in parallel because containers operate on the same
files, which would result in them conflicting.

Also update `.gitignore` to exclude build files from git.

Jira ref: OAMG-2251

2022-09-15 16:06 UTC, pirat89 requested changes
@matejmatuska `clean_containers` is defined twice, each with different functionality.
```
$ make clean_containers 
Makefile:238: warning: overriding recipe for target 'clean_containers'
Makefile:178: warning: ignoring old recipe for target 'clean_containers'
```

2022-09-16 09:39 UTC, matejmatuska commented
@pirat89 I must have merged incorrectly, it's fixed now.

2022-09-21 17:06 UTC, pirat89 requested changes

2022-09-21 17:06 UTC, pirat89 commented on Makefile
> +	[ $${_CONT_FILE:0:1} = '.' ] && rm -f res/container-builds/$$_CONT_FILE
@matejmatuska  If the condition result to false, the make commands ends with error and non-zero exit code which could be confusing.
```suggestion
	[ '$${_CONT_FILE:0:1}' = '.' ] && rm -f res/container-builds/$$_CONT_FILE || :
```

When fixed, we can merge it. Everything else seems to be working right.

2022-09-23 09:05 UTC, pirat89 approved these changes

2022-09-23 09:06 UTC, merged