Add reports summary to the output
oamg/leapp pull request #818
Opened 2023-03-17 10:11 UTC by matejmatuska

Previously only the paths to reports were printed and as a result the reports were easily missed.

Leapp now prints a list of HIGH and MEDIUM priority reports along with a summary of number of reports with individual severities to make reports more visible.

### Example of the new output:
![Screenshot from 2023-03-17 11-05-27](https://user-images.githubusercontent.com/75834032/225874583-857cd72e-e53b-4fd0-b374-5bb225c404ef.png)

2023-03-22 15:47 UTC, matejmatuska commented on leapp/utils/output.py
> +    high = [
Seems like inhibitors don't have to be high severity, we only enforce that during reviews in leapp-repository so I think we should assume they can as the framework allows it.

Anyway going with the suggestion, thanks!

2023-03-31 10:15 UTC, fernflower commented
/rerun

2023-03-31 10:16 UTC, fernflower reviewed
Codewise looks ok, let's see how regression tests do with output format change.

2023-04-05 09:44 UTC, pirat89 requested changes, later dismissed
the changed API requires bump of leapp-framework capability, however, I am not fully sure the change in the API is needed - so do not change it yet. I will do the proper review in upcoming days.

Here is the doc reference: https://leapp.readthedocs.io/en/latest/compatibility-with-leapp-repository.html

2023-04-12 16:02 UTC, pirat89 commented
/packit build

2023-04-12 16:51 UTC, pirat89 commented
Seeing also white text in case of errors or inhibitors:

![screenshot_report_error](https://user-images.githubusercontent.com/1656374/231524548-265cd1c4-c795-4c78-8e77-78feafce9f2b.png)

I am now thinking whether we want to stay with  the white color in such case or whether we want to use the yellow/red in such cases. WDYT guys? @oamg/developers

2023-04-12 16:55 UTC, pirat89 commented
@matejmatuska btw, regarding the API, I see it's needed here. So the leapp-framework capability should be bumped from 3.1 to 4.0 as it's incompatible with the previous one right now. requirements in leapp-repository needs to be updated then also.

2023-05-16 09:54 UTC, fernflower approved these changes, later dismissed
lgtm!

2023-05-16 09:54 UTC, fernflower commented
/rerun

2023-05-17 08:27 UTC, fernflower commented
Hmmm the tests are failing upon artifact installation, 
```
Problem: package leapp-upgrade-el8toel9-0.18.0-100.20230511140705049292.master.24.g24bfccc.el8.noarch requires leapp-framework < 4, but none of the providers can be installed
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.20230504143926109663.pr826.8.gbce420b.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.20230504181959398697.pr827.22.g7099099.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.20230505103819842857.pr827.22.g05abcfe.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.20230505120552826380.pr827.23.geeaa2c6.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.20230505125657797257.pr828.7.g374584a.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.202305051257Z.374584a.HEAD.PR828.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.20230505130737588050.pr828.7.ga1b899e.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.20230505133904547525.pr828.8.gf6c65eb.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.202305051344Z.f6c65eb.HEAD.PR828.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.20230507055151424808.pr826.8.gf5e9371.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.202305090900Z.f6c65eb.HEAD.PR828.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.202305090940Z.f5e9371.HEAD.PR826.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.202305091329Z.07ff6eb.HEAD.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.202305091517Z.032c009.HEAD.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-0.20230515174545881278.pr829.11.g2cc4901.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-100.20230509133631293244.master.8.g07ff6eb.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-100.20230509151611316346.master.10.g032c009.el8.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.0-1.el8_6.1.noarch
  - cannot install both python3-leapp-0.15.1-0.202305160955Z.0d530a3.HEAD.PR818.el8.noarch and python3-leapp-0.15.1-1.el8_6.2.noarch
  - conflicting requests
```

2023-05-17 08:28 UTC, fernflower commented
I will remove approval for now until it's clear to me what's causing it.

2023-05-17 09:02 UTC, fernflower commented
/rerun

2023-05-17 09:36 UTC, fernflower commented
/rerun 1061

2023-05-17 11:31 UTC, fernflower commented
/rerun 1061

2023-05-18 10:44 UTC, fernflower commented
Codewise lgtm, regression tests that rely on checking leapp report output require minor tuning due to obvious reasons (like 'Inhibitor: some message' being changed to 'some message' under inhibitors section) so I'd wait for QE's good to go. @mm0ran @mmacura311

2023-05-18 10:45 UTC, fernflower approved these changes

2023-05-29 11:04 UTC, fernflower commented
/rerun 1061

2023-06-13 09:54 UTC, dkubek commented
/packit copr-build

2023-06-23 09:41 UTC, fernflower commented
/rerun 1061

2023-07-11 08:38 UTC, dkubek commented
/packit copr-build

2023-07-17 17:21 UTC, merged